// What systemd 259 (Fedora 44, 259.5-1.fc44) sets from each of these files as a unit's EnvironmentFile=, measured for
// issue #447 with `systemd-run --wait -p EnvironmentFile=<file> /usr/bin/env -0` (system scope). Columns: name, the file,
// the venue keys the unit saw (PI_BACKENDS, PI_EGRESS, PI_EGRESS_PROXY; null when systemd refused to LOAD the file and
// the unit failed), the line and shape this module reports, and what `bash -c 'set -a; . ./file'` exported (gate round 1
// rows only; null where not measured). The reported column is pinned beside the measurement so a change to either is a
// change to this table. Every text is written with escapes; no raw control byte is in this file.
//
// Row names: r- the issue's shapes (refused), q- probes of the edges around them, c- identifier-key multi-line values
// `quotedRegions` already models, p- lines that must keep reading as they do, g1- the gate round 1 adversary's files
// and the UTF-8/NUL probes measured beside them.
export const SYSTEMD_259_ENV_FILES = Object.freeze([
	["r-reopen-dq","K=\"a\"\"b\nPI_BACKENDS=podman\n\"\n",{},[1,"reopened-quote"],null],
	["r-reopen-dq-space","K=\"a\" \"b\nPI_BACKENDS=podman\n\"\n",{},[1,"reopened-quote"],null],
	["r-reopen-dq-tab","K=\"a\"\t\"b\nPI_BACKENDS=podman\n\"\n",{},[1,"reopened-quote"],null],
	["r-reopen-sq","K='a''b\nPI_BACKENDS=podman\n'\n",{},[1,"reopened-quote"],null],
	["r-reopen-sq-space","K='a' 'b\nPI_BACKENDS=podman\n'\n",{},[1,"reopened-quote"],null],
	["r-reopen-mixed","K=\"a\"'b\nPI_BACKENDS=podman\n'\n",{},[1,"reopened-quote"],null],
	["r-reopen-twice","K=\"a\" \"b\" \"c\nPI_BACKENDS=podman\n\"\n",{},[1,"reopened-quote"],null],
	["r-reopen-on-close-line","K=\"a\nb\" \"c\nPI_BACKENDS=podman\n\"\n",{},[2,"reopened-quote"],null],
	["r-reopen-on-close-line-nospace","K=\"a\nb\"\"c\nPI_BACKENDS=podman\n\"\n",{},[2,"reopened-quote"],null],
	["r-reopen-nonident","FOO-BAR=\"a\" \"b\nPI_BACKENDS=podman\n\"\n",{},[1,"reopened-quote"],null],
	["r-key-dash","FOO-BAR=\"x\nPI_BACKENDS=podman\n\"\n",{},[1,"non-identifier-key"],null],
	["r-key-dot","FOO.BAR=\"x\nPI_BACKENDS=podman\n\"\n",{},[1,"non-identifier-key"],null],
	["r-key-digit","1FOO=\"x\nPI_BACKENDS=podman\n\"\n",{},[1,"non-identifier-key"],null],
	["r-key-space","FOO BAR=\"x\nPI_BACKENDS=podman\n\"\n",{},[1,"non-identifier-key"],null],
	["r-key-dash-sq","FOO-BAR='x\nPI_BACKENDS=podman\n'\n",{},[1,"non-identifier-key"],null],
	["r-key-dash-leading-ws","  FOO-BAR=\"x\nPI_BACKENDS=podman\n\"\n",{},[1,"non-identifier-key"],null],
	["r-key-dash-space-before-quote","FOO-BAR= \"x\nPI_BACKENDS=podman\n\"\n",{},[1,"non-identifier-key"],null],
	["r-key-quote-in-key","FOO\"BAR=\"x\nPI_BACKENDS=podman\n\"\n",{},[1,"non-identifier-key"],null],
	["q-key-eq-first","=a=\"x\nPI_BACKENDS=podman\n\"\n",{},[1,"non-identifier-key"],null],
	["r-key-unclosed-eof","FOO-BAR=\"x\nPI_BACKENDS=podman\n",{},[1,"non-identifier-key"],null],
	["r-lone-cr","X=1\rPI_BACKENDS=podman\n",{"PI_BACKENDS":"podman"},[1,"lone-cr"],null],
	["q-cr-in-dq","K=\"a\rb\"\nPI_BACKENDS=podman\n",{"PI_BACKENDS":"podman"},null,null],
	["q-cr-cr-lf","X=1\r\r\nPI_BACKENDS=podman\n",{"PI_BACKENDS":"podman"},[1,"lone-cr"],null],
	["q-cont-after-close","K=\"a\"\\\nPI_BACKENDS=podman\n",{},null,null],
	["q-cont-after-region-close","K=\"a\nb\"\\\nPI_BACKENDS=podman\n",{},[2,"continuation"],null],
	["q-cont-after-region-close-value","K=\"a\nb\"x\\\nPI_BACKENDS=podman\n",{},[2,"continuation"],null],
	["q-cont-crlf","K=a\\\r\nPI_BACKENDS=podman\r\n",{"PI_BACKENDS":"podman"},null,null],
	["c-ident-unclosed","K=\"x\nPI_BACKENDS=podman\n\"\n",{},null,null],
	["c-export-unclosed","export K=\"x\nPI_BACKENDS=podman\n\"\n",{},null,null],
	["c-ident-space-key","K =\"x\nPI_BACKENDS=podman\n\"\n",{},null,null],
	["p-dq-then-char","K=\"a\"b\nPI_BACKENDS=podman\n",{"PI_BACKENDS":"podman"},null,null],
	["p-mid-quotes","K=a\"b\"c\nPI_BACKENDS=podman\n",{"PI_BACKENDS":"podman"},null,null],
	["p-comment-quote","K=\"a\" # \"b\nPI_BACKENDS=podman\n",{"PI_BACKENDS":"podman"},null,null],
	["p-comment-quote-closed","K=\"a\" # \"b\"\nPI_BACKENDS=podman\n",{"PI_BACKENDS":"podman"},null,null],
	["p-notes","K=\"/a.json\" # see \"notes\"\nPI_BACKENDS=podman\n",{"PI_BACKENDS":"podman"},null,null],
	["p-sq-then-char","K='a'b'\nPI_BACKENDS=podman\n",{"PI_BACKENDS":"podman"},null,null],
	["p-reopen-closes","K=\"a\" \"b\"\nPI_BACKENDS=podman\n",{"PI_BACKENDS":"podman"},null,null],
	["p-pem","GITHUB_APP_PRIVATE_KEY=\"-----BEGIN RSA PRIVATE KEY-----\nMIIEpAIBAAKCAQEA0Z3VS5JJcds3xfn/ygWyF8PbnGy0AHB7MaNtRE0l\n-----END RSA PRIVATE KEY-----\"\nPI_BACKENDS=podman\n",{"PI_BACKENDS":"podman"},null,null],
	["p-crlf","K=1\r\nPI_BACKENDS=podman\r\n",{"PI_BACKENDS":"podman"},null,null],
	["p-cr-eof","K=1\nPI_BACKENDS=podman\r",{"PI_BACKENDS":"podman"},null,null],
	["p-key-dash-plain","FOO-BAR=x\nPI_BACKENDS=podman\n",{"PI_BACKENDS":"podman"},null,null],
	["p-key-dash-closed","FOO-BAR=\"x\"\nPI_BACKENDS=podman\n",{"PI_BACKENDS":"podman"},null,null],
	["p-key-dash-midquote","FOO-BAR=x \"y\nPI_BACKENDS=podman\n",{"PI_BACKENDS":"podman"},null,null],
	["p-region-close-then-char-quote","K=\"a\nb\" x \"c\nPI_BACKENDS=podman\n",{"PI_BACKENDS":"podman"},null,null],
	["p-region-close-then-char","K=\"a\nb\"c\"\nPI_BACKENDS=podman\n",{"PI_BACKENDS":"podman"},null,null],
	["p-comment-hash","# FOO-BAR=\"x\nPI_BACKENDS=podman\n",{"PI_BACKENDS":"podman"},null,null],
	["p-comment-semicolon","; FOO-BAR=\"x\nPI_BACKENDS=podman\n",{"PI_BACKENDS":"podman"},null,null],
	["p-no-eq","FOO \"BAR\nPI_BACKENDS=podman\n",{"PI_BACKENDS":"podman"},null,null],
	["q-eq-first","=\"x\nPI_BACKENDS=podman\n\"\n",{"PI_BACKENDS":"podman"},null,null],
	["q-cont-midvalue-dq","K=a\"b\\\nPI_BACKENDS=podman\n",{},[1,"continuation"],null],
	["q-cont-midvalue-sq","K='a'b'\\\nPI_BACKENDS=podman\n",{},[1,"continuation"],null],
	["q-cont-midvalue-sq2","K=a'b\\\nPI_BACKENDS=podman\n",{},[1,"continuation"],null],
	["q-cont-after-hash","K=\"a\" # \"b\\\nPI_BACKENDS=podman\n",{},[1,"continuation"],null],
	["q-cont-hash-plain","K=a # b\\\nPI_BACKENDS=podman\n",{},[1,"continuation"],null],
	["q-cont-nonident","FOO-BAR=a\"b\\\nPI_BACKENDS=podman\n",{},[1,"continuation"],null],
	["q-cont-plain","K=a\\\nPI_BACKENDS=podman\n",{},null,null],
	["p-comment-backslash","# note\\\nPI_BACKENDS=podman\n",{"PI_BACKENDS":"podman"},null,null],
	["q-cont-inside-region","K=\"a\\\nb\"\nPI_BACKENDS=podman\n",{"PI_BACKENDS":"podman"},null,null],
	["q-cr-in-comment","# note\rPI_BACKENDS=podman\n",{"PI_BACKENDS":"podman"},[1,"lone-cr"],null],
	["q-cr-in-sq","K='a\rb'\nPI_BACKENDS=podman\n",{"PI_BACKENDS":"podman"},null,null],
	["c-key-on-close-line","NOTE=\"see\nPI_BACKENDS=\"podman\"\n",{},null,null],
	["p-comment-backslash-semicolon","  ; note\\\nPI_BACKENDS=podman\n",{"PI_BACKENDS":"podman"},null,null],
	["q-cont-into-hash-line","K=a\\\n# b\\\nPI_BACKENDS=podman\n",{},null,null],
	["g1-a01-u2028-dq","PI_EGRESS=0\nX=\"a\u2028b\nPI_EGRESS=1\n\"\n",{"PI_EGRESS":"0"},null,{"PI_EGRESS":"0"}],
	["g1-a02-midcr-dq","PI_EGRESS=0\nX=\"a\rb\nPI_EGRESS=1\n\"\n",{"PI_EGRESS":"0"},null,{"PI_EGRESS":"0"}],
	["g1-a03-u2029-sq-backends","PI_BACKENDS=local\nX='a\u2029\nPI_BACKENDS=podman\n'\n",{"PI_BACKENDS":"local"},null,{"PI_BACKENDS":"local"}],
	["g1-a04-u2028-proxy","PI_EGRESS_PROXY=http://good:3128\nX=\"\u2028\nPI_EGRESS_PROXY=http://evil:3128\n\"\n",{"PI_EGRESS_PROXY":"http://good:3128"},null,{"PI_EGRESS_PROXY":"http://good:3128"}],
	["g1-a09-hash-comment-bs","PI_EGRESS=1\n# c\\\nPI_EGRESS=0\n",{"PI_EGRESS":"0"},null,{"PI_EGRESS":"0"}],
	["g1-a10-semi-comment-bs","PI_EGRESS=1\n; c\\\nPI_EGRESS=0\n",{"PI_EGRESS":"0"},null,{"PI_EGRESS":"1"}],
	["g1-a11-export","export PI_EGRESS=0\n",{},null,{"PI_EGRESS":"0"}],
	["g1-a12-bom-first","\ufeffPI_EGRESS=0\n",{},null,{}],
	["g1-a13-nbsp-lead","\u00a0PI_EGRESS=0\n",{},null,{}],
	["g1-a14-vt-lead","\u000bPI_EGRESS=0\n",{},null,{}],
	["g1-a15-ff-lead","\fPI_EGRESS=0\n",{},null,{}],
	["g1-a16-crlf-cont","X=a\\\r\nPI_EGRESS=0\r\n",{"PI_EGRESS":"0"},null,{"PI_EGRESS":"0\r"}],
	["g1-a17-ws-bs-line","PI_EGRESS=1\n \\\nPI_EGRESS=0\n",{"PI_EGRESS":"0"},null,{"PI_EGRESS":"0"}],
	["g1-a18-no-trailing-nl","PI_EGRESS=0",{"PI_EGRESS":"0"},null,{"PI_EGRESS":"0"}],
	["g1-a19-dq-escquote","PI_EGRESS=0\nX=\"a\\\"\nPI_EGRESS=1\n\"\n",{"PI_EGRESS":"0"},null,{"PI_EGRESS":"0"}],
	["g1-a20-sq-bs","PI_EGRESS=0\nX='a\\\nPI_EGRESS=1\n'\n",{"PI_EGRESS":"0"},null,{"PI_EGRESS":"0"}],
	["g1-a21-cont-then-dq","PI_EGRESS=0\nX=\\\n\"abc\nPI_EGRESS=1\n\"\n",{"PI_EGRESS":"1"},null,{"PI_EGRESS":"0"}],
	["g1-a22-cont-then-opener","PI_EGRESS=1\nX=a\\\nY=\"b\nPI_EGRESS=0\n\"\n",{"PI_EGRESS":"0"},[3,"unmodelled-quote"],{"PI_EGRESS":"1"}],
	["g1-a23-shell-twoassign","X=a PI_EGRESS=0\n",{},null,{"PI_EGRESS":"0"}],
	["g1-a24-shell-dollarsq","PI_EGRESS=0\nX=$'a\\'b\nPI_EGRESS=1\nY=1' #'\n",{"PI_EGRESS":"1"},null,{"PI_EGRESS":"0"}],
	["g1-a25-tab-eq","PI_EGRESS\t=0\n",{"PI_EGRESS":"0"},null,{}],
	["g1-a26-cr-eof","PI_EGRESS=1\nPI_EGRESS=0\r",{"PI_EGRESS":"0"},null,{"PI_EGRESS":"0\r"}],
	["g1-a27-dq-bs-nl-close","PI_EGRESS=0\nX=\"a\nb\"\\\nPI_EGRESS=1\n",{"PI_EGRESS":"0"},[3,"continuation"],{"PI_EGRESS":"0"}],
	["g1-a28-hash-in-dq-region","PI_EGRESS=0\nX=\"a # \nPI_EGRESS=1 #\"\n",{"PI_EGRESS":"0"},null,{"PI_EGRESS":"0"}],
	["g1-a29-emptykey","PI_EGRESS=0\n=\"a\nPI_EGRESS=1\n\"\n",{"PI_EGRESS":"1"},null,{"PI_EGRESS":"0"}],
	["g1-a30-u2028-after-close","PI_EGRESS=0\nX=\"a\"\u2028\"b\nPI_EGRESS=1\n\"\n",{"PI_EGRESS":"1"},null,{"PI_EGRESS":"0"}],
	["g1-a31-cr-in-region-then-quote","PI_EGRESS=0\nX=\"a\nb\r\"\nPI_EGRESS=1\n",{"PI_EGRESS":"1"},null,{"PI_EGRESS":"1"}],
	["g1-a32-export-u2028","PI_EGRESS=0\nexport X=\"\u2028\nPI_EGRESS=1\n\"\n",{"PI_EGRESS":"0"},null,{"PI_EGRESS":"0"}],
	["g1-a33-u2028-key-trail","PI_EGRESS=0\nX\u2028=\"a\nPI_EGRESS=1\n\"\n",{"PI_EGRESS":"0"},[2,"non-identifier-key"],{"PI_EGRESS":"0"}],
	["g1-a34-semicolon-key","PI_EGRESS=1\nPI_EGRESS=0;x\n",{"PI_EGRESS":"0;x"},null,{"PI_EGRESS":"0"}],
	["g1-b06-fffd-valid","X=a\ufffdb\nPI_EGRESS=1\n",{"PI_EGRESS":"1"},null,{"PI_EGRESS":"1"}],
	["g1-d1-cont-into-quote-line","K=x\\\nB=\"z\nK=\"y\nPI_BACKENDS=podman\n",{},[2,"unmodelled-quote"],{"PI_BACKENDS":"podman"}],
	["g1-d2-comment-bs-then-nonident","# x\\\nFOO-BAR=\"y\nPI_BACKENDS=podman\n\"\n",{},[2,"non-identifier-key"],{}],
	["g1-d3-dq-escaped-quote-nonident","FOO-BAR=\"a\\\"\nPI_BACKENDS=podman\n\"\n",{},[1,"non-identifier-key"],{}],
	["g2-b15-c1-valid","PI_EGRESS=1\nX='\u0080'\n",{"PI_EGRESS":"1"},null,{"PI_EGRESS":"1"}],
	["g2-b17-nonchar-in-comment","PI_EGRESS=1\n# \uffff\n",{"PI_EGRESS":"1"},null,{"PI_EGRESS":"1"}],
	["g2-b40-dq-trailing-ws","PI_EGRESS=\"0\" \t\n",{"PI_EGRESS":"0"},null,{"PI_EGRESS":"0"}],
	["g2-b41-bare-trailing-tab-crlf","PI_EGRESS=0\t\r\n",{"PI_EGRESS":"0"},null,{}],
	["g2-b42-dq-inner-space","PI_BACKENDS=\" podman\"\n",{"PI_BACKENDS":" podman"},null,{"PI_BACKENDS":" podman"}],
	["g2-b43-sq-trailing-ws-crlf","PI_BACKENDS='podman'  \r\n",{"PI_BACKENDS":"podman"},null,{}],
	["g2-b44-dup-last-wins","PI_EGRESS=0\nPI_EGRESS=1\n",{"PI_EGRESS":"1"},null,{"PI_EGRESS":"1"}],
	["g2-b45-empty-dq","PI_EGRESS=\"\"\n",{"PI_EGRESS":""},null,{"PI_EGRESS":""}],
	["g2-b46-value-nbsp-trail","PI_BACKENDS=podman\u00a0\n",{"PI_BACKENDS":"podman\u00a0"},null,{"PI_BACKENDS":"podman\u00a0"}],
	["g2-b47-value-u2028-sq","PI_BACKENDS='podman\u2028'\n",{"PI_BACKENDS":"podman\u2028"},null,{"PI_BACKENDS":"podman\u2028"}],
	["g2-b50-sh-cont-twoassign","X=a\\\n PI_EGRESS=0\n",{},null,{"PI_EGRESS":"0"}],
	["g2-b51-sh-cont-semicolon","X=a\\\n;PI_EGRESS=0\n",{},null,{"PI_EGRESS":"0"}],
	["g2-b52-sh-cont-hash-semicolon","X=a\\\n#;PI_EGRESS=0\n",{},null,{"PI_EGRESS":"0"}],
	["g2-b53-sh-cont-dollarsq","PI_EGRESS=0\nX=$\\\n'a\\'b\nPI_EGRESS=1\nY=1' #'\n",{"PI_EGRESS":"1"},null,{"PI_EGRESS":"0"}],
	["g2-b54-sh-cont-run","X=a\\\n;PI_BACKENDS=podman\n",{},null,{"PI_BACKENDS":"podman"}],
	["g2-w01-cont-eof","A=1\nX=a\\\nPI_BACKENDS=podman\n",{},null,{}],
	["g2-w02-unclosed-dq-eof","A=1\nX=\"abc\nPI_BACKENDS=podman\n",{},null,{}],
	["g2-w03-commented-key-in-region","X=\"abc\nPI_BACKENDS=podman\n\"\n",{},null,{}],
	["g2-w04-crlf","A=1\r\nB=2\r\nPI_BACKENDS=podman\n",{"PI_BACKENDS":"podman"},null,{"PI_BACKENDS":"podman"}],
	["g2-w05-no-trailing-nl","A=1\nPI_BACKENDS=podman\n",{"PI_BACKENDS":"podman"},null,{"PI_BACKENDS":"podman"}],
	["g2-w06-bom","\ufeffA=1\nPI_BACKENDS=podman\n",{"PI_BACKENDS":"podman"},null,{"PI_BACKENDS":"podman"}],
	["g2-w07-cr-eof","A=1\r\nPI_BACKENDS=podman\n",{"PI_BACKENDS":"podman"},null,{"PI_BACKENDS":"podman"}],
	["g2-w08-crlf-empty-key","A=1\r\nPI_BACKENDS=podman\r\nB=2\r\n",{"PI_BACKENDS":"podman"},null,{"PI_BACKENDS":"podman\r"}],
	["g2-w09-commented-key-after-cont","X=a\\\nPI_BACKENDS=podman\n",{},null,{}],
	["g2-w10-commented-key","A=1\nPI_BACKENDS=podman\n",{"PI_BACKENDS":"podman"},null,{"PI_BACKENDS":"podman"}],
	["g2-w13-unclosed-sq-eof","A=1\nX='abc\nPI_BACKENDS=podman\n",{},null,{}],
	["g2-w14-cont-no-nl","A=1\nX=a\\",{},null,{}],
	["g2-s01-semicolon-oneline","X=a;PI_EGRESS=0\n",{},null,{"PI_EGRESS":"0"}],
	["g2-s02-amp-oneline","X=a&&PI_EGRESS=0\n",{},null,{"PI_EGRESS":"0"}],
	["g2-s03-pipe-oneline","X=a|PI_EGRESS=0\n",{},null,{}],
	["g2-u04-fdcf-ok","PI_EGRESS=1\nX=a\ufdcfb\n",{"PI_EGRESS":"1"},null,{"PI_EGRESS":"1"}],
	["g2-u05-fdf0-ok","PI_EGRESS=1\nX=a\ufdf0b\n",{"PI_EGRESS":"1"},null,{"PI_EGRESS":"1"}],
	["g2-u09-nonchar-in-no-eq","PI_EGRESS=1\n\uffff\n",{"PI_EGRESS":"1"},null,{"PI_EGRESS":"1"}],
	["g3-c10-dq-hex","PI_EGRESS=1\nX=\"\\x41|\\101|\u00e9|\\n|\\t|\\\\|\\$|\\a\"\n",{"PI_EGRESS":"1"},null,{"PI_EGRESS":"1"}],
	["g3-c11-dq-hex-ff","PI_EGRESS=1\nX=\"\\xff\"\n",{"PI_EGRESS":"1"},null,{"PI_EGRESS":"1"}],
	["g3-c12-dq-octal-377","PI_EGRESS=1\nX=\"\\377\"\n",{"PI_EGRESS":"1"},null,{"PI_EGRESS":"1"}],
	["g3-c14-bare-hex-ff","PI_EGRESS=1\nX=\\xff\n",{"PI_EGRESS":"1"},null,{"PI_EGRESS":"1"}],
	["g3-c15-sq-hex-ff","PI_EGRESS=1\nX='\\xff'\n",{"PI_EGRESS":"1"},null,{"PI_EGRESS":"1"}],
	["g3-c17-dq-x00","PI_EGRESS=1\nX=\"\\x00\"\n",{"PI_EGRESS":"1"},null,{"PI_EGRESS":"1"}],
	["g3-c18-dq-backslash-u","PI_EGRESS=1\nX=\"\\u00e9|\\uFFFE\"\n",{"PI_EGRESS":"1"},null,{"PI_EGRESS":"1"}],
	["g3-c19-bare-backslash-u","PI_EGRESS=1\nX=\\uFFFE\n",{"PI_EGRESS":"1"},null,{"PI_EGRESS":"1"}],
	["g3-w01-cont-eof-up","A=1\nX=a\\\n",{},null,{}],
	["g3-w01-cont-eof-wizard","A=1\nX=a\\\n",{},null,{}],
	["g3-w02-unclosed-dq-eof-up","A=1\nX=\"abc\n",{},null,{}],
	["g3-w02-unclosed-dq-eof-wizard","A=1\nX=\"abc\n",{},null,{}],
	["g3-w03-commented-key-in-region-up","X=\"abc\n# PI_BACKENDS=\n\"\nWEBHOOK_SECRET=deadbeef\n",{},null,{}],
	["g3-w03-commented-key-in-region-wizard","X=\"abc\n# PI_BACKENDS=\n\"\nPI_BACKENDS=podman\n",{"PI_BACKENDS":"podman"},null,{"PI_BACKENDS":"podman"}],
	["g3-w04-crlf-up","A=1\r\nB=2\r\nWEBHOOK_SECRET=deadbeef\n",{},null,{}],
	["g3-w04-crlf-wizard","A=1\r\nB=2\r\nPI_BACKENDS=podman\n",{"PI_BACKENDS":"podman"},null,{"PI_BACKENDS":"podman"}],
	["g3-w05-no-trailing-nl-up","A=1\nWEBHOOK_SECRET=deadbeef\n",{},null,{}],
	["g3-w05-no-trailing-nl-wizard","A=1\nPI_BACKENDS=podman\n",{"PI_BACKENDS":"podman"},null,{"PI_BACKENDS":"podman"}],
	["g3-w06-bom-up","\ufeffA=1\nWEBHOOK_SECRET=deadbeef\n",{},null,{}],
	["g3-w06-bom-wizard","\ufeffA=1\nPI_BACKENDS=podman\n",{"PI_BACKENDS":"podman"},null,{"PI_BACKENDS":"podman"}],
	["g3-w07-cr-eof-up","A=1\r\nWEBHOOK_SECRET=deadbeef\n",{},null,{}],
	["g3-w07-cr-eof-wizard","A=1\r\nPI_BACKENDS=podman\n",{"PI_BACKENDS":"podman"},null,{"PI_BACKENDS":"podman"}],
	["g3-w08-crlf-empty-key-up","A=1\r\nPI_BACKENDS=\r\nB=2\r\nWEBHOOK_SECRET=deadbeef\n",{"PI_BACKENDS":""},null,{"PI_BACKENDS":"\r"}],
	["g3-w08-crlf-empty-key-wizard","A=1\r\nPI_BACKENDS=podman\r\nB=2\r\n",{"PI_BACKENDS":"podman"},null,{"PI_BACKENDS":"podman\r"}],
	["g3-w09-commented-key-after-cont-up","X=a\\\n# PI_BACKENDS=\nWEBHOOK_SECRET=deadbeef\n",{},null,{"PI_BACKENDS":""}],
	["g3-w09-commented-key-after-cont-wizard","X=a\\\n# PI_BACKENDS=\nPI_BACKENDS=podman\n",{"PI_BACKENDS":"podman"},null,{"PI_BACKENDS":"podman"}],
	["g3-w10-commented-key-up","A=1\n# PI_BACKENDS=\nWEBHOOK_SECRET=deadbeef\n",{},null,{}],
	["g3-w10-commented-key-wizard","A=1\nPI_BACKENDS=podman\n",{"PI_BACKENDS":"podman"},null,{"PI_BACKENDS":"podman"}],
	["g3-w13-unclosed-sq-eof-up","A=1\nX='abc\n",{},null,{}],
	["g3-w13-unclosed-sq-eof-wizard","A=1\nX='abc\n",{},null,{}],
	["g3-w20-comment-bs-no-nl-up","A=1\n# note\\\nWEBHOOK_SECRET=deadbeef\n",{},null,{}],
	["g3-w20-comment-bs-no-nl-wizard","A=1\n# note\\\nPI_BACKENDS=podman\n",{"PI_BACKENDS":"podman"},null,{"PI_BACKENDS":"podman"}],
	["g3-w21-comment-bs-nl-up","A=1\n# note\\\nWEBHOOK_SECRET=deadbeef\n",{},null,{}],
	["g3-w21-comment-bs-nl-wizard","A=1\n# note\\\nPI_BACKENDS=podman\n",{"PI_BACKENDS":"podman"},null,{"PI_BACKENDS":"podman"}],
	["g3-w22-comment-bs-crlf-no-nl-up","A=1\r\n# note\\\r\nWEBHOOK_SECRET=deadbeef\n",{},null,{}],
	["g3-w22-comment-bs-crlf-no-nl-wizard","A=1\r\n# note\\\r\nPI_BACKENDS=podman\n",{"PI_BACKENDS":"podman"},null,{"PI_BACKENDS":"podman"}],
	["g3-w23-crlf-bs-eof-up","A=1\r\nX=a\\\r\n",{},null,{}],
	["g3-w23-crlf-bs-eof-wizard","A=1\r\nX=a\\\r\n",{},null,{}],
	["g3-w24-crlf-no-nl-up","A=1\r\nB=2\nWEBHOOK_SECRET=deadbeef\n",{},null,{}],
	["g3-w24-crlf-no-nl-wizard","A=1\r\nB=2\nPI_BACKENDS=podman\n",{"PI_BACKENDS":"podman"},null,{"PI_BACKENDS":"podman"}],
	["g3-w25-semicolon-comment-bs-up","A=1\n; note\\\nWEBHOOK_SECRET=deadbeef\n",{},null,{}],
	["g3-w25-semicolon-comment-bs-wizard","A=1\n; note\\\nPI_BACKENDS=podman\n",{"PI_BACKENDS":"podman"},null,{}],
	["g3-w26-comment-key-crlf-up","A=1\r\n# PI_BACKENDS=\r\nWEBHOOK_SECRET=deadbeef\n",{},null,{}],
	["g3-w26-comment-key-crlf-wizard","A=1\r\nPI_BACKENDS=podman\r\n",{"PI_BACKENDS":"podman"},null,{"PI_BACKENDS":"podman\r"}],
]);

// Files that are not valid UTF-8 text or carry a NUL, as hex bytes, with the load hazard `envFileLoadHazard` reports.
export const SYSTEMD_259_ENV_BYTES = Object.freeze([
	["g1-a05-nul-comment","50495f4547524553533d300a2320000a50495f4547524553533d310a",null,[2,"nul"],{"PI_EGRESS":"1"}],
	["g1-a06-nul-value","50495f4547524553533d300a583d6100620a50495f4547524553533d310a",null,[2,"nul"],{"PI_EGRESS":"1"}],
	["g1-a07-badutf8-value","50495f4547524553533d300a583dff0a50495f4547524553533d310a",null,[2,"invalid-utf8"],{"PI_EGRESS":"1"}],
	["g1-a08-badutf8-key","50495f4547524553533d300aff3d310a50495f4547524553533d310a",null,[2,"invalid-utf8"],{"PI_EGRESS":"1"}],
	["g1-b01-badutf8-comment","23206e6f746520ff0a50495f4547524553533d310a",{"PI_EGRESS":"1"},null,{"PI_EGRESS":"1"}],
	["g1-b02-badutf8-noeq","6a756e6b20ff0a50495f4547524553533d310a",{"PI_EGRESS":"1"},null,{"PI_EGRESS":"1"}],
	["g1-b03-badutf8-dq-value","583d2261ff62220a50495f4547524553533d310a",null,[1,"invalid-utf8"],{"PI_EGRESS":"1"}],
	["g1-b04-badutf8-region","583d22610aff0a220a50495f4547524553533d310a",null,[1,"invalid-utf8"],{"PI_EGRESS":"1"}],
	["g1-b05-nul-at-eof","50495f4547524553533d310a00",null,[2,"nul"],{"PI_EGRESS":"1"}],
	["g1-b07-overlong","583dc0af0a50495f4547524553533d310a",null,[1,"invalid-utf8"],{"PI_EGRESS":"1"}],
	["g1-b08-surrogate","583deda0800a50495f4547524553533d310a",null,[1,"invalid-utf8"],{"PI_EGRESS":"1"}],
	["g1-b09-badutf8-semicolon-comment","3b20fe0a50495f4547524553533d310a",{"PI_EGRESS":"1"},null,{}],
	["g2-b01-overlong2-value","50495f4547524553533d310a583dc0800a",null,[2,"invalid-utf8"],{"PI_EGRESS":"1"}],
	["g2-b02-overlong3-value","50495f4547524553533d310a583de080800a",null,[2,"invalid-utf8"],{"PI_EGRESS":"1"}],
	["g2-b03-surrogate-value","50495f4547524553533d310a583deda0800a",null,[2,"invalid-utf8"],{"PI_EGRESS":"1"}],
	["g2-b04-5byte-value","50495f4547524553533d310a583df8888080800a",null,[2,"invalid-utf8"],{"PI_EGRESS":"1"}],
	["g2-b05-6byte-value","50495f4547524553533d310a583dfc84808080800a",null,[2,"invalid-utf8"],{"PI_EGRESS":"1"}],
	["g2-b06-trunc-eof-value","50495f4547524553533d310a583d61e282",null,[2,"invalid-utf8"],{"PI_EGRESS":"1"}],
	["g2-b07-bad-in-comment","50495f4547524553533d310a2320ff0a",{"PI_EGRESS":"1"},null,{"PI_EGRESS":"1"}],
	["g2-b08-bad-no-eq-line","50495f4547524553533d310aff0a",{"PI_EGRESS":"1"},null,{"PI_EGRESS":"1"}],
	["g2-b09-bad-in-key","50495f4547524553533d310a58ff3d310a",null,[2,"invalid-utf8"],{"PI_EGRESS":"1"}],
	["g2-b10-nonchar-fffe","50495f4547524553533d310a583d61efbfbe0a",null,[2,"invalid-utf8"],{"PI_EGRESS":"1"}],
	["g2-b11-nonchar-fdd0","50495f4547524553533d310a583d61efb7900a",null,[2,"invalid-utf8"],{"PI_EGRESS":"1"}],
	["g2-b12-nonchar-1ffff","50495f4547524553533d310a583d61f09fbfbf0a",null,[2,"invalid-utf8"],{"PI_EGRESS":"1"}],
	["g2-b13-above-10ffff","50495f4547524553533d310a583df49080800a",null,[2,"invalid-utf8"],{"PI_EGRESS":"1"}],
	["g2-b14-bs-split-seq","50495f4547524553533d310a583de25c82820a",{"PI_EGRESS":"1"},null,{"PI_EGRESS":"1"}],
	["g2-b16-trunc-eof-comment","50495f4547524553533d310a232061e282",{"PI_EGRESS":"1"},null,{"PI_EGRESS":"1"}],
	["g2-b18-bad-in-sq-region","50495f4547524553533d310a583d27610aff0a270a",null,[2,"invalid-utf8"],{"PI_EGRESS":"1"}],
	["g2-b19-nonchar-ffff-key","50495f4547524553533d310a58efbfbf3d310a",null,[2,"invalid-utf8"],{"PI_EGRESS":"1"}],
	["g2-b20-nonchar-in-venue-sq","50495f4241434b454e44533d27706f646d616eefbfbe270a",null,[1,"invalid-utf8"],{"PI_BACKENDS":"podman\ufffe"}],
	["g2-w15-nonchar-other","413d78efbfbe0a50495f4241434b454e44533d706f646d616e0a",null,[1,"invalid-utf8"],{"PI_BACKENDS":"podman"}],
	["g2-u01-ffff-value","50495f4547524553533d310a583d61efbfbf620a",null,[2,"invalid-utf8"],{"PI_EGRESS":"1"}],
	["g2-u02-fdd0-value","50495f4547524553533d310a583d61efb790620a",null,[2,"invalid-utf8"],{"PI_EGRESS":"1"}],
	["g2-u03-fdef-value","50495f4547524553533d310a583d61efb7af620a",null,[2,"invalid-utf8"],{"PI_EGRESS":"1"}],
	["g2-u06-10fffe-value","50495f4547524553533d310a583d61f48fbfbe620a",null,[2,"invalid-utf8"],{"PI_EGRESS":"1"}],
	["g2-u07-dq-split-valid","50495f4547524553533d310a583d22c32222a9220a",{"PI_EGRESS":"1"},null,{"PI_EGRESS":"1"}],
	["g2-u08-dq-escape-split","50495f4547524553533d310a583d22c35ca9220a",null,[2,"invalid-utf8"],{"PI_EGRESS":"1"}],
	["g3-c13-dq-u-fffe","50495f4547524553533d310a583d22efbfbe220a",null,[2,"invalid-utf8"],{"PI_EGRESS":"1"}],
	["g3-w15-nonchar-other-up","413d78efbfbe0a",null,[1,"invalid-utf8"],{}],
	["g3-w15-nonchar-other-wizard","413d78efbfbe0a",null,[1,"invalid-utf8"],{}],
]);
