import assert from "node:assert/strict";
import { closeSync, fstatSync, fsyncSync, ftruncateSync, linkSync, mkdirSync, openSync, readFileSync, renameSync, statSync, symlinkSync, writeFileSync, writeSync } from "node:fs";
import { join } from "node:path";
import { test } from "node:test";
import { endpointsFileSetting, reloadCommand, runEgress, writeInPlace } from "../src/egress-cli.mjs";
import { renderEndpointsInclude } from "../src/model-endpoints.mjs";
import { main } from "../src/cli.mjs";
import { tempDir } from "./helpers/temp-dir.mjs";

const ONE = { version: 1, endpoints: [{ id: "mac-ollama", host: "host.docker.internal", port: 11434, slots: 2, keyless: true }] };

// The golden for ONE, as the shipped proxy reads it (the render itself is pinned in model-endpoints.test.mjs).
const GOLDEN_ONE = [
	"# Generated by pi-dispatch from model-endpoints.json. Do not edit: regenerate it with `pi-dispatch egress render`.",
	"# Each endpoint is a CONNECT tunnel to exactly one declared host and port, and nothing else (issue #503).",
	"# The host ACL comes first on every line, so squid only ever resolves a declared name.",
	"",
	"# mac-ollama",
	"acl pde_mac-ollama_host dstdomain -n host.docker.internal",
	"acl pde_mac-ollama_port port 11434",
	"acl pde_mac-ollama_local dst 127.0.0.0/8 0.0.0.0/32 10.0.2.2/32 ::1 ::/128",
	"http_access deny CONNECT pde_mac-ollama_host pde_mac-ollama_port pde_mac-ollama_local",
	"http_access allow CONNECT pde_mac-ollama_host pde_mac-ollama_port",
	"",
].join("\n");

/** A deployment folder: the endpoints file, the scaffolded empty include, and an optional .env. */
function deployment({ endpoints = ONE, envText = null, include = renderEndpointsInclude([]) } = {}) {
	const dir = tempDir("pd-egress-cli-");
	if (endpoints !== null) writeFileSync(join(dir, "model-endpoints.json"), JSON.stringify(endpoints));
	if (include !== null) writeFileSync(join(dir, "model-endpoints.conf"), include);
	if (envText !== null) writeFileSync(join(dir, ".env"), envText);
	return dir;
}

async function render(dir, { env = {}, platform = "linux", ...rest } = {}) {
	let out = "";
	let err = "";
	const code = await runEgress(["render"], { env, cwd: dir, platform, out: (s) => (out += s), err: (s) => (err += s), valkeyUrl: () => "redis://127.0.0.1:6379", ...rest });
	return { code, out, err };
}

test("egress render writes the include IN PLACE: same inode, the golden text, and the docker reload printed (#503)", async () => {
	const dir = deployment();
	const path = join(dir, "model-endpoints.conf");
	const before = statSync(path).ino;
	const r = await render(dir);
	assert.equal(r.code, 0, r.err);
	assert.equal(readFileSync(path, "utf8"), GOLDEN_ONE);
	// The measured reason (Docker 29.1.3, Podman 4.9.3 and 5.8.1 on Linux): a single-file bind mount holds the inode,
	// so only a write to the SAME inode is what the running proxy reloads.
	assert.equal(statSync(path).ino, before, "the include keeps its inode");
	assert.match(r.out, /wrote .*model-endpoints\.conf \(in place\)/);
	assert.match(r.out, /^ {2}docker exec pi-dispatch-egress-proxy squid -k reconfigure$/m);
	assert.doesNotMatch(r.out, /\b(docker|podman) restart\b/, "a reconfigure, never a restart");
});

test("egress render: an unchanged include is not written and says so (#503)", async () => {
	const dir = deployment({ include: GOLDEN_ONE });
	let wrote = 0;
	const r = await render(dir, { write: () => wrote++ });
	assert.equal(r.code, 0);
	assert.equal(wrote, 0);
	assert.match(r.out, /already matches the declared model endpoints: nothing written/);
});

test("egress render refuses a symlink, a directory and a missing include, and writes nothing (#503)", async () => {
	const linked = deployment({ include: null });
	writeFileSync(join(linked, "real.conf"), "keep\n");
	symlinkSync(join(linked, "real.conf"), join(linked, "model-endpoints.conf"));
	const a = await render(linked);
	assert.equal(a.code, 1);
	assert.match(a.err, /is a symlink/);
	assert.equal(readFileSync(join(linked, "real.conf"), "utf8"), "keep\n", "nothing written through the link");

	const dird = deployment({ include: null });
	mkdirSync(join(dird, "model-endpoints.conf"));
	const b = await render(dird);
	assert.equal(b.code, 1);
	assert.match(b.err, /is a directory, not a file/);

	const missing = deployment({ include: null });
	const c = await render(missing);
	assert.equal(c.code, 1);
	assert.match(c.err, /does not exist: `pi-dispatch init`/);
	assert.throws(() => statSync(join(missing, "model-endpoints.conf")), /ENOENT/, "a missing include is not created");
});

test("egress render validates before it truncates: a refused declaration leaves the include as it was (#503)", async () => {
	const dir = deployment({ endpoints: { version: 1, endpoints: [{ id: "lo", host: "127.0.0.1", port: 11434, slots: 1 }] }, include: GOLDEN_ONE });
	const r = await render(dir);
	assert.equal(r.code, 1);
	assert.match(r.err, /model-endpoints\.conf was not changed/);
	assert.equal(readFileSync(join(dir, "model-endpoints.conf"), "utf8"), GOLDEN_ONE);
});

test("writeInPlace keeps the inode where a temp file renamed over the path does not (#503)", () => {
	const dir = tempDir("pd-egress-inplace-");
	const path = join(dir, "model-endpoints.conf");
	writeFileSync(path, "old\n");
	const ino = statSync(path).ino;
	writeInPlace(path, "new and longer\n");
	assert.equal(readFileSync(path, "utf8"), "new and longer\n");
	assert.equal(statSync(path).ino, ino);
	writeInPlace(path, "s\n");
	assert.equal(readFileSync(path, "utf8"), "s\n", "truncated, not overlaid");
	// The control: what the render must NOT do.
	writeFileSync(join(dir, "tmp"), "renamed\n");
	renameSync(join(dir, "tmp"), path);
	assert.notEqual(statSync(path).ino, ino);
	assert.throws(() => writeInPlace(join(dir, "absent.conf"), "x"), /ENOENT/, "never creates a file");
});

test("egress render names the reload per venue: podman for the rootless venue, both for both, the operator's own proxy (#503)", async () => {
	const podman = await render(deployment(), { env: { PI_BACKENDS: "podman" } });
	assert.match(podman.out, /^ {2}podman exec pi-dispatch-egress-proxy squid -k reconfigure$/m);
	assert.doesNotMatch(podman.out, /docker exec/);
	const both = await render(deployment(), { env: { PI_BACKENDS: "local,podman" } });
	assert.match(both.out, /docker exec pi-dispatch-egress-proxy squid -k reconfigure/);
	assert.match(both.out, /podman exec pi-dispatch-egress-proxy squid -k reconfigure/);
	const own = await render(deployment(), { env: { PI_EGRESS_PROXY: "my-squid" } });
	assert.match(own.out, /docker exec my-squid squid -k reconfigure/);
	assert.match(own.out, /my-squid is your own proxy/);
	const off = await render(deployment(), { env: { PI_EGRESS: "0" } });
	assert.equal(off.code, 0);
	assert.match(off.out, /egress policy is off/);
	assert.doesNotMatch(off.out, /squid -k reconfigure/);
	assert.equal(reloadCommand("podman", "x"), "podman exec x squid -k reconfigure");
});

test("egress render reads PI_MODEL_ENDPOINTS_FILE from .env, and refuses a shell value that disagrees with it (#503)", async () => {
	const dir = deployment({ endpoints: null, envText: "PI_MODEL_ENDPOINTS_FILE=elsewhere.json\n" });
	writeFileSync(join(dir, "elsewhere.json"), JSON.stringify(ONE));
	const r = await render(dir);
	assert.equal(r.code, 0, r.err);
	assert.equal(readFileSync(join(dir, "model-endpoints.conf"), "utf8"), GOLDEN_ONE);
	assert.deepEqual(endpointsFileSetting({ env: {}, cwd: dir }), { value: "elsewhere.json", note: null });
	const clash = await render(dir, { env: { PI_MODEL_ENDPOINTS_FILE: "other.json" } });
	assert.equal(clash.code, 1);
	assert.match(clash.err, /in this shell and "elsewhere\.json" in .*\.env/);
});

test("pi-dispatch egress: usage lists `egress render`, and an unknown subcommand exits 1 (#503)", async () => {
	let usage = "";
	assert.equal(await main([], {}, { write: (s) => (usage += s) }), 0);
	assert.match(usage, /pi-dispatch egress render\n/);
	let help = "";
	assert.equal(await main(["egress", "--help"], {}, { write: (s) => (help += s) }), 0);
	assert.match(help, /in place/);
	assert.equal(await runEgress(["frob"], { err: () => {}, out: () => {} }), 1);
	assert.equal(await runEgress(["render", "extra"], { err: () => {}, out: () => {} }), 1);
});

// --- round-1 gate of PR #517 ---------------------------------------------------------------------------------------------

test("writeInPlace EMPTIES the include when the write fails after the truncate, never leaving it half written (#503 gate A517-2)", () => {
	const dir = tempDir("pd-egress-empty-");
	const path = join(dir, "model-endpoints.conf");
	writeFileSync(path, "old rules\n");
	let writes = 0;
	const failing = { openSync, fstatSync, ftruncateSync, fsyncSync, closeSync, writeSync: (fd, b, off, len) => (writes++ === 0 ? writeSync(fd, b, off, Math.min(len, 20)) : (() => { throw Object.assign(new Error("ENOSPC: no space left on device"), { code: "ENOSPC" }); })()) };
	assert.throws(() => writeInPlace(path, "x".repeat(100), failing), (e) => e.code === "ENOSPC" && e.emptied === true);
	assert.equal(readFileSync(path, "utf8"), "", "empty, which squid reads as no endpoints, not a prefix");
});

test("egress render says EMPTIED when its write failed, and refuses a hard-linked include without touching it (#503 gate A517-2, A517-5)", async () => {
	const dir = deployment();
	const r = await render(dir, { write: () => { throw Object.assign(new Error("EIO"), { code: "EIO", emptied: true }); } });
	assert.equal(r.code, 1);
	assert.match(r.err, /It was EMPTIED rather than left half written, which closes every declared endpoint until a render succeeds/);
	const linked = deployment({ include: "before\n" });
	linkSync(join(linked, "model-endpoints.conf"), join(linked, "other-name.conf"));
	const l = await render(linked);
	assert.equal(l.code, 1);
	assert.match(l.err, /has 2 hard links: a write in place would change every one of them[^\n]*It was not changed/);
	assert.equal(readFileSync(join(linked, "other-name.conf"), "utf8"), "before\n");
});

test("egress render compares PI_MODEL_ENDPOINTS_FILE as paths, and warns when only this shell sets it (#503 gate)", async () => {
	const dir = deployment({ endpoints: null, envText: "PI_MODEL_ENDPOINTS_FILE=elsewhere.json\n" });
	writeFileSync(join(dir, "elsewhere.json"), JSON.stringify(ONE));
	const same = await render(dir, { env: { PI_MODEL_ENDPOINTS_FILE: "./elsewhere.json" } });
	assert.equal(same.code, 0, same.err);
	const shellOnly = deployment({ endpoints: null });
	writeFileSync(join(shellOnly, "mine.json"), JSON.stringify(ONE));
	const r = await render(shellOnly, { env: { PI_MODEL_ENDPOINTS_FILE: "mine.json" } });
	assert.equal(r.code, 0);
	assert.match(r.out, /⚠ PI_MODEL_ENDPOINTS_FILE comes from this shell only, and the service reads .*\.env, which does not set it/);
});

test("egress render's words: off says no reload; unchanged names the reload as an if; a refused declaration with no include says nothing was written (#503 gate)", async () => {
	const off = await render(deployment({ include: GOLDEN_ONE }), { env: { PI_EGRESS: "0" } });
	assert.match(off.out, /nothing written/);
	assert.doesNotMatch(off.out, /reload it as below|reload it/i);
	const same = await render(deployment({ include: GOLDEN_ONE }));
	assert.match(same.out, /If the proxy started before it last changed, reload it \(no restart[^\n]*\n {2}docker exec pi-dispatch-egress-proxy squid -k reconfigure/);
	const bad = { version: 1, endpoints: [{ id: "lo", host: "127.0.0.1", port: 11434, slots: 1 }] };
	const none = await render(deployment({ endpoints: bad, include: null }));
	assert.match(none.err, /Nothing was written\./);
	assert.doesNotMatch(none.err, /was not changed/);
});

test("egress render names the rules refresh when endpoints are declared and the rules the proxy runs predate #503, per venue (#503 gate L517-2)", async () => {
	const PRE = "http_port 3128\n";
	const INCL = "http_port 3128\ninclude /etc/pi-dispatch/model-endpoints.conf\n";
	const docker = deployment();
	mkdirSync(join(docker, "deploy"));
	writeFileSync(join(docker, "deploy", "egress-proxy.conf"), PRE);
	const d = await render(docker);
	assert.match(d.out, /⚠ model endpoints are declared, but deploy\/egress-proxy\.conf predates #503 and does not include model-endpoints\.conf, so the endpoints stay unreachable until the rules are refreshed: `pi-dispatch up`, and accept the refresh/);
	writeFileSync(join(docker, "deploy", "egress-proxy.conf"), INCL);
	assert.doesNotMatch((await render(docker)).out, /predates #503/);
	const home = tempDir("pd-egress-home-");
	mkdirSync(join(home, ".config", "pi-dispatch"), { recursive: true });
	writeFileSync(join(home, ".config", "pi-dispatch", "egress-proxy.conf"), PRE);
	const p = await render(deployment(), { env: { PI_BACKENDS: "podman" }, home });
	assert.match(p.out, /⚠ model endpoints are declared, but the podman proxy's rules \(~\/\.config\/pi-dispatch\/egress-proxy\.conf\) predate #503[^\n]*`pi-dispatch service install --force`/);
	// No endpoints declared: nothing to say.
	const empty = deployment({ endpoints: { version: 1, endpoints: [] } });
	mkdirSync(join(empty, "deploy"));
	writeFileSync(join(empty, "deploy", "egress-proxy.conf"), PRE);
	assert.doesNotMatch((await render(empty)).out, /predates #503/);
});
